# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Api\:
        resource: '../src/Api/*'
        exclude:
            - '../src/Api/{DependencyInjection,Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Api\Controller\:
        resource: '../src/Api/Controller'
        tags: ['controller.service_arguments']

    App\Application\:
        resource: '../src/Application/*'
        exclude:
            - '../src/Application/{Command}'

    App\Application\Service\AbstractService:
        abstract: true
        calls:
            - [setCommandValidator, ['@validator']]

    App\Infrastructure\:
      resource: '../src/Infrastructure/*'

    App\Infrastructure\ArgumentResolver\RequestDtoValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
